config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

  resources :trails do
    resources :reviews
  end
  resources :parks
  resources :reviews

  # get "/login", to: "sessions#new", as: "login"
  # post "/login", to: "sessions#create"

  # get "/parks/:id/reviews" to: "reviews#new"

  # delete "/logout", to: "sessions#destroy", as: "destroy_user_session"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


# enoch lecture
# https://youtu.be/7u21R9T9vdQ?t=176

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :trails
  has_many :reviews, through: :trails
  has_many :users, through: :reviews

  accepts_nested_attributes_for :trails
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :trail
  
  

  # REVIEW_DIFFICULTY = ["Easy", "Moderate", "Hard"]
  # REVIEW_RATING = ["1", "2", "3", "4", "5"]

  # validates :content, length: { maximum: 500 }
  # validate :difficulty_is_valid?
  # validate :rating_is_valid?

  # def difficulty_is_valid?
  #   if !REVIEW_DIFFICULTY.include?(self.difficulty)
  #     self.errors.add(:difficulty, "must select difficulty to submit")
  #   end
  # end

  # def rating_is_valid?
  #   if !REVIEW_RATING.include?(self.rating)
  #     self.errors.add(:rating, "must select a rating to submit")
  #   end
  # end
end

app/models/trail.rb
class Trail < ApplicationRecord
  belongs_to :park
  has_many :reviews
  has_many :users, through: :reviews

  # REVIEW_DIFFICULTY = ["Easy", "Moderate", "Hard"]
  # REVIEW_RATING = ["1", "2", "3", "4", "5"]

  # validate :difficulty_is_valid?
  # validate :rating_is_valid?

  # def difficulty_is_valid?
  #   if !REVIEW_DIFFICULTY.include?(self.difficulty)
  #     self.errors.add(:difficulty, "must select difficulty to submit")
  #   end
  # end

  # def rating_is_valid?
  #   if !REVIEW_RATING.include?(self.rating)
  #     self.errors.add(:rating, "must select a rating to submit")
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :reviews
  has_many :trails, through: :reviews

  before_save :downcase_email
  

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  

  private
  def downcase_email
    self.email = self.email.downcase
  end
end

app/controllers/application_controller.rb
# require './config/enviorment'

class ApplicationController < ActionController::Base

  # helper_method :user_signed_in?, :current_user

  # def user_signed_in?
  #   !!session[:user_id]
  # end

  # def current_user
  #   User.find_by_id(session[:user_id]) if user_signed_in?
  # end

  # def login_user
  #   session[:user_id] = @user.id
  # end

  # # configure do 
  # #   enable :sessions
  # #   set :public_folder, 'public'
  # #   set :views, 'app/views'
  # #   set :session_secret, "hotdog"
  # #   end
end

# class ApplicationController < ActionController::Base
#   # helper_method :logged_in?, :current_user
#   # before_action :authenticate_user!

#   # def current_user
#   #   if session[:user_id]
#   #     @current_user = User.find(session[:user_id])
#   #   end
#   # end

#   # def logged_in?
#   #   !!current_user
#   # end

# end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def show
   @park = Park.find_by_id(params[:id])
   @trail = Trail.find_by(params[:park_id])
  end

  def index
    @parks = Park.all
  end





  # private

  # def park_params
  #   params.require(:park).permit(:name, :location, trails_attributes [:id, :name, :length, :difficulty])
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
include ReviewHelper

def new
  @review = Review.new
  find_trail_by_id(:trail_id)
end

def create
  @review = Review.new(review_params)
  @user = current_user
  user_reviewed(@user)
  @trail = @review.trail_id
  if @review.save
    flash[:notice] = "Your review was successfully posted"
    redirect_to review_path(@review)
  else 
    flash[:notice] = "Review could not be created. Please check the errors."
    render 'new'
  end
end

def show
  @review = Review.find(params[:id])
  @user_reviewed = User.find_by(params[:id])
  @trail = @review.trail_id
end

def index
  find_trail_by_id(:trail_id)
  # @trail = Trail.find(params[:trail_id])
  @reviews = Review.where(:trail_id == @trail)
  @user_reviewed = User.find_by(params[:id])
end

private

def review_params
  params.require(:review).permit(
    :content, 
    :trail_id,
    :user_id
  )
end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

def show
  @trail = Trail.find_by_id(params[:id])
  @reviews = Review.where(:trail_id == @trail.id)
  user_reviewed(@user)
end

def index
  @trail = Trail.all
end 

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_nav_links
    content_tag("ul", class: "right") do 
      if user_signed_in?
        content_tag("li") do 
          link_to("Parks", parks_path)
        end +
        content_tag("li") do
          link_to("Create new review", new_review_path)
        end +
        content_tag("li") do
          link_to("Logout", destroy_user_session_path, method: "DELETE")
        end
      else
        content_tag("li") do
          link_to("Login", new_user_session_path)
        end +
        content_tag("li") do
          link_to("Signup", new_user_registration_path)
        end +
        content_tag("li") do
          link_to("Sign in with Facebook", user_facebook_omniauth_authorize_path, method: :post)
        end
      end
    end
  end
end

app/helpers/hiker_helper.rb
module HikerHelper
end

app/helpers/park_helper.rb
module ParkHelper
end

app/helpers/review_helper.rb
module ReviewHelper

def find_trail_by_id(trail_id)
  @trail = Trail.find(params[:trail_id])
end

def user_reviewed(user)
  User.find_by(params[:id])
end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trail_helper.rb
module TrailHelper
end

app/views/layouts/_errors.html.erb
<% if flash[:error] %>
<% flash[:error].each do |error| %>
<p><%= error %></p>
<% end %>
<% end %>

<%= content_tag("p", flash[:notice]) if flash[:notice] %>

app/views/layouts/_nav.html.erb
<nav class="<%= navbar_color %>">
  <div class="container">
    <%= link_to("SimpleHike", root_path, class: "brand-logo") %>
    <ul class="right">
      <%= render_nav_links %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simplehike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/latest/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'layouts/nav', locals: { navbar_color: "indigo darken-3"} %>
  <%= render 'layouts/errors' %>
  
  <div class="container">
    <%= yield %>
    
    </div>
  </body>
</html>

app/views/parks/_form.html.erb
<%= form_with model: @park, local: true do |f| %>
    ...
    <fieldset>
        <legend>Trails:</legend>
        <%= f.fields_for :trails do |review_form| %>
            <%= render "review_fields", f: review_form %>
        <% end %>
        <%= link_to_add_fields "Add Review", f, :trails %>
    </fieldset>

    <%= f.submit %>
<% end %>

app/views/parks/_review_fields.html.erb
<div class="nested-fields">
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :length %>
        <%= f.number_field :length %>
    </div>
    <div>
      <%= f.label :difficulty %>
      <%= f.text_field :difficulty%>
    </div>
    <div>
        <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/parks/index.html.erb
<h1><b>List of all parks</b></h1>
<br>
<br>

<% @parks.each do |foo| %>
<ul>
 <li><%=link_to foo.name, park_path(foo)%></li>

<li>Location: <%=foo.location %></li>
</ul>
<% end %>

app/views/parks/reviewtest.html.erb
<h1>List of all Parks</h1>

<% form_for(@park) do |park| %>
<%= park.label "Name" %>
<%= park.text_field :name %>
<%= park.label "Location" %>
<%= park.text_field :location %>

<% park.fields_for :trails do |t| %>
<%= t.collection_select(:trail_id, Trail.all, :id, :name) %>
<% end %>

<%= park.submit "Post" %>

<% end %>

app/views/parks/show.html.erb
<h1>This page shows 1 park and its trails</h1>

<h2><%= @park.name %></h2>
<table class="center, striped">
<thead>
<tr>
<th>Name</th>
<th>Length</th>
<th>Difficulty</th>
<th>Rating</th>
<th>Review</th>
</tr>
<% @park.trails.each do |trail| %>
</tr>
</thead>

<tbody>
<tr>
<td><%= link_to trail.name, trail_path(trail) %></td>
<td><%= trail.length %> Miles</td>
<td><%= trail.difficulty %></td>
<td><%= trail.rating %></td>
<td><%= link_to "Show All Reviews", trail_reviews_url(trail) %></td>
<td><%= link_to "New Review", new_trail_review_url(trail) %></td>
</tr>


<% end %>
</tr>
</tbody>
</table>

app/views/reviews/index.html.erb
<h1><b>List of all reviews for <%= @trail.name %></h1>
<h2><%= link_to "Leave a New Review", new_trail_review_url(@trail) %></h2>


<% @reviews.each do |review| %>
<% if review.trail_id == @trail.id %> 
<ul>
 Here's what <%= @user_reviewed.name %> had to say about this dumb trail: 
 <br>
<%= review.content %>
</ul>
<% else %>
<% end %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add A New Review <%= @trail.name %> </h1> 

<%= form_for @review do |r| %>

<%= r.hidden_field :user_id, value: current_user.id %>
<%= r.hidden_field :trail_id, value: @trail.id %>

<h1>Tell me about your stupid hike</h1>

<p><%= r.label :content %>
<%= r.text_field :content %></p>
<br>
<br>

<p><%= r.submit "Submit" %></p>
<% end %>

app/views/reviews/show.html.erb
<%# This page shows one review after submission of a new review %>

<h1>Showing selected review</h1>
<p>
 Trail: <%= @review.trail.name %>
</p>
<p>
  Difficulty <%= @review.trail.difficulty.capitalize %>
</p>
<p>
 Here's what <%= @user_reviewed.name %> had to say about this dumb trail: 
 <br>
 <h1><%= @review.content %></h1>
</p>

<%= link_to "See what others had to say about this trail", trail_reviews_url(@trail) %>

app/views/trails/index.html.erb
<h1>List of all Trails</h1>

<% @trail.all.each do |t| %>
<div class="container">
<ul>
<li><%= t.name %></li>
<li><%=t.length %></li>
<li><%=t.difficulty %></li>
<li><%=t.rating %></li>
<li><%=t.park_id %></li>
</ul>
<% end %>
</div>

app/views/trails/show.html.erb
<h1>This page shows one trail and its details/reveiws</h1>

<br>
<div class="container">
<ul> 
<li>Name: <%= @trail.name %></li>
<li>Rating: <%= @trail.rating %></li>
<li>Difficulty: <%= @trail.difficulty %></li>
<li>Length: <%= @trail.length %></li>
<%= link_to "New Review", new_trail_review_url(@trail) %>
</ul>
</div>

Here's what other hiker's had to say about the trails in this dumb park: 
<% @reviews.each do |review| %>
<% if review.trail_id == @trail.id %> 

<ul>
<li><%= review.content %> - <%= @user_reviewed.name %></li>
</ul>
<% else %>
<% end %>
<% end %>